#!/bin/bash
#
# makefont - Font Builder
# Written in 2015-2017 by Saber Rasetikerdar <saber.rastikerdar@gmail.com>
#
# Requirements:
#     build.py
#     ttfautohint
#     sfnt2woff
#     ttf2eot
#     woff2_compress
#     zip
#

if [ ! -f "build.conf" ]; then
    echo "build.conf not found!"
    exit 1
fi

source build.conf

SCRIPTDIR=`dirname "$0"`
TEMPDIR="${PWD}/font-output-temp"
SOURCEDIR="source"
LATINDIR="latin"
DISTDIR="dist"
BUILDCMD="${SCRIPTDIR}"/build.py

if [ ! -f "${BUILDCMD}" ]; then
    echo "BUILDCMD not found!"
    exit 1
fi

if [ ! -d "${SOURCEDIR}" ]; then
    echo "SOURCEDIR not found!"
    exit 1
fi

if [ ! -f "${BUILDCMD}" ]; then
    echo "BUILDCMD not found!"
    exit 1
fi

rm -rf "${TEMPDIR}"
mkdir -p "${TEMPDIR}"
mkdir "${TEMPDIR}"/build

if [ ! -d "${TEMPDIR}"/build ]; then
    echo "TEMPDIR/build not found!"
    exit 1
fi

# Make all the possible versions
for ((i=0;i<${#SOURCEFILES[@]};++i));
do
  sf="$SOURCEDIR"/"${SOURCEFILES[i]}"
  lf="${LATINDIR}"/"${LATINFILES[i]}"
  bn=$(basename ${sf})
  filename="${bn%.*}"
  if [ -f ${sf} ]; then  
    "${BUILDCMD}" --input="${sf}" --output="${TEMPDIR}"/build/$filename-WOL.ttf
    "${BUILDCMD}" --input="${sf}" --output="${TEMPDIR}"/build/$filename-FD-WOL.ttf --farsi-digits
    if [ -f ${lf} ]; then  
      "${BUILDCMD}" --input="${sf}" --latin="${lf}" --output="${TEMPDIR}"/build/$filename.ttf
      "${BUILDCMD}" --input="${sf}" --latin="${lf}" --output="${TEMPDIR}"/build/$filename-FD.ttf --farsi-digits
    fi
  fi 
done

# Make all file types
for f in "${TEMPDIR}"/build/*.ttf
do
  if [ -f "${f}" ]; then
    fn=$(basename "${f}")
    ttfautohint -n -w D -W -D arab -f latn -G 11 -l 8 -r 11 "${f}" "${TEMPDIR}/${fn}"
    sfnt2woff "${TEMPDIR}/${fn}"
    ttf2eot "${TEMPDIR}/${fn}" > "${TEMPDIR}/${fn%%.*}".eot
    woff2_compress "${TEMPDIR}/${fn}"
  fi 
done
rm -rf "${TEMPDIR}"/build

# Move files to where they belong to
mkdir "${TEMPDIR}"/Farsi-Digits-Without-Latin
mv "${TEMPDIR}"/*FD-WOL* "${TEMPDIR}"/Farsi-Digits-Without-Latin

mkdir "${TEMPDIR}"/Farsi-Digits
mv "${TEMPDIR}"/*FD* "${TEMPDIR}"/Farsi-Digits

mkdir "${TEMPDIR}"/Without-Latin
mv "${TEMPDIR}"/*WOL* "${TEMPDIR}"/Without-Latin

# Add other(license, readme, ...) files defined in build.conf
for ((i=0;i<${#ADDFILES[@]};++i));
do
  cp "${ADDFILES[i]}" "${TEMPDIR}"
done

# Make the release package(zip)
rm -f "$RELEASEFILEPATH"
CURDIR=`pwd`
cd "${TEMPDIR}"
zip -r release.zip .
cd "$CURDIR"
mv "${TEMPDIR}"/release.zip "$RELEASEFILEPATH"

# Make folder "dist"
mkdir -p "${DISTDIR}"
cp -rf "${TEMPDIR}"/**/ "${DISTDIR}"
cp -rf "${TEMPDIR}"/*.woff "${DISTDIR}"
cp -rf "${TEMPDIR}"/*.woff2 "${DISTDIR}"
cp -rf "${TEMPDIR}"/*.ttf "${DISTDIR}"
cp -rf "${TEMPDIR}"/*.eot "${DISTDIR}"

# Clean up
rm -rf "${TEMPDIR}"